name: Deploy to Production
on:
    push:
        branches: [main]
    workflow_dispatch:
        inputs:
            deploy_target:
                description: 'Environment to run deployment against'
                type: environment
                default: 'Production'
                required: true

jobs:
    test:
        uses: ./.github/workflows/test.yml
    
    deploy:
        environment: Production
        name: Deploy to Production
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: configure SSH
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.DIGITAL_OCEAN }}" > ~/.ssh/deploy_key.pem
                chmod 600 ~/.ssh/deploy_key.pem
                cat >> ~/.ssh/config <<END
                Host my-vps
                    HostName ${{ secrets.SSH_IP}}
                    User ${{ secrets.SSH_USER }}
                    IdentityFile ~/.ssh/deploy_key.pem
                    StrictHostKeyChecking no
                END
              env:
                DIGITAL_OCEAN: ${{ secrets.DIGITAL_OCEAN }}
                SSH_USER: ${{ secrets.SSH_USER }}
                SSH_IP: ${{ secrets.SSH_IP }}
            # - name: Print working directory
            #   run: ssh my-vps 'cd $secrets.PROJECT_ROOT && pwd'
            - name: Deploy Site
              run: ssh my-vps 'cd ${{ secrets.PROJECT_ROOT }} && ~/redeploy-site.sh'
            - name: Container Status
              run: ssh my-vps 'docker ps'
            - name: Check Logs
              run: ssh my-vps 'docker logs myportfolio'
            - name: Discord webhook notification for failure
              if: ${{ failure() }}
              run: |
                RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
                "username": "GitHub",
                "content": "@everyone",
                "embeds": [
                  {
                    "type": "rich",
                    "title": "🚨🚨 Deployment Failed 🚨🚨",
                    "description": "Deployment to Production was unsuccessful, ran by ${{ github.actor }}",
                    "color": 16711680,
                    "thumbnail": {
                      "url": "https://github.com/user-attachments/assets/63a02b87-34a4-42d2-8aed-9cd9ce8aca12"
                    },
                    "author": {
                      "name": "${{ github.actor }}",
                      "url": "https://github.com/${{ github.actor_id }}",
                      "icon_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
                    },
                    "url": "https://github.com/${{ github.repository }}"
                    }
                    ]
                  }' ${{ secrets.DISCORD_WEBHOOK }})
                echo "Webhook server response: $RESPONSE"
            - name: Discord webhook notification for success
              if: ${{ success() }}
              run: |
                RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
                "username": "GitHub",
                "content": "@everyone",
                "embeds": [
                {
                    "type": "rich",
                    "title": "Deployment Successful 🚀🚀",
                    "description": "Deployment to Production successful by ${{ github.actor }}",
                    "color": 339966,
                    "thumbnail": {
                    "url": "https://github.com/user-attachments/assets/63a02b87-34a4-42d2-8aed-9cd9ce8aca12"
                    },
                    "author": {
                    "name": "${{ github.actor }}",
                    "url": "https://github.com/${{ github.actor_id }}",
                    "icon_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
                    },
                    "url": "https://github.com/${{ github.repository }}"
                    }
                    ]
                }' ${{ secrets.DISCORD_WEBHOOK }})
                echo "Webhook server response: $RESPONSE"


