name: Run Tests
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        name: Run Tests
        env:
            TESTING: true
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10.18'
            - name: Setup Python Virtual Environment
              run: python -m venv python3-virtualenv
            - name: Install Dependencies
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt
                source python3-virtualenv/bin/activate
            - name: Run Tests
              run: ./run_tests.sh
